### Post one country
POST http://localhost:3000/api/countries HTTP/1.1
Content-Type: application/json

{
    "name": "Germany",
    "capital": "Berlin",
    "population": 83129285
}

### Post another single country
POST http://localhost:3000/api/countries HTTP/1.1
Content-Type: application/json

{
    "name": "France",
    "capital": "Paris",
    "population": 67422000
}

### Delete one country
DELETE http://localhost:3000/api/countries/Germany HTTP/1.1

### Delete another country
DELETE http://localhost:3000/api/countries/France HTTP/1.1

### Get all countries
GET http://localhost:3000/api/countries HTTP/1.1
